server:
  port: 9000

spring:
  #  控制台彩色输出
  output:
    ansi:
      enabled: always
    #  配置数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8
    username: root
    password: AngelBeats
  application:
    name: user-service #服务提供应用名

#配置mybatis plus
mybatis-plus:
  type-aliases-package: com.provider.pojo

#配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka #注册服务地址
  instance:
    prefer-ip-address: true #更倾向于使用ip，而不是host名
    ip-address: 127.0.0.1 #ip地址
    lease-renewal-interval-in-seconds: 5 #续约间隔，默认30秒
    lease-expiration-duration-in-seconds: 10  #服务失效时间，默认90秒

#配置日志级别
logging:
  level:
    com.provider: debug